### ISSUE TITLE
Will this be updated to 1.17?

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Hendrix-Shen/Tweak-My-Client#1]

**Comment by Hendrix-Shen** [comment]
It will be updated soon, but we should wait for malilib to be compatible

**Comment by DragonEggBedrockBreaking** [comment]
Malilib is compatible already. https://github.com/maruohon/malilib/tree/fabric_1.17.x

**Comment by Hendrix-Shen** [comment]
Updated.
