### ISSUE TITLE
自动攀爬功能失效

### ISSUE THREAD

**Issue by fractures202** [Hendrix-Shen/Tweak-My-Client#10]
游戏版本1.18.2 mod版本 TweakMyClient-3.0.235+a155763-stable

**Comment by Hendrix-Shen** [comment]
尝试下 [3.1.237+015247d](https://github.com/Hendrix-Shen/Tweak-My-Client/releases/tag/dev-237) 版本。
Curseforge 文件列表可能需要若干分钟同步。
