### ISSUE TITLE
(BUG REPORT) disableSlowdown make you slower when swimming

### ISSUE THREAD

**Issue by MarkinhosMLP** [Hendrix-Shen/Tweak-My-Client#11]
tested in 1.18.2 version of the mod, when disableSlowdown option is ON, when you are swimming you goes REALLY REALLY slow, but when turning this option off, the swimming speed goes back to normal

**Comment by MarkinhosMLP** [comment]
it stills slowing you down, but the ebrries are working perfectly xD

**Comment by Hendrix-Shen** [comment]
I tested a walking horizontal axis speed of `1.960 m/s` in water and a swimming speed of `3.920 m/s` in water, with or without `disableSlowdown` enabled. Can you give me more information?

**Comment by MarkinhosMLP** [comment]
welp... the default swimming speed is 5.6 m/s which is faster than the normal walking speed (4.3m/s) and of course faster then walking on the water speed (1.965 m/s)
ill record it in a video and send to show it

**Comment by MarkinhosMLP** [comment]
https://user-images.githubusercontent.com/47507632/174354825-a512a812-2e56-40ed-9ae8-0cf7d1220335.mp4

**Comment by Hendrix-Shen** [comment]
Sorry, I think I need some time to research this issue.

**Comment by MarkinhosMLP** [comment]
idk if it has something about the disableSwimming option, but before it was added it used to work well
> as you can see disableSwimming is not active in this case

**Comment by MarkinhosMLP** [comment]
Seems to be fixed in the last version of the mod, idk how or why but yeah thats good
