### ISSUE TITLE
(BUG REPORT) disableSlowdown and berries

### ISSUE THREAD

**Issue by MarkinhosMLP** [Hendrix-Shen/Tweak-My-Client#12]
disableSlowdown option does not remove the slowdown for walking in sweet berry bushes

**Comment by Hendrix-Shen** [comment]
Actually, it's not a bug, but I'll add this feature.

**Comment by Hendrix-Shen** [comment]
Try this version [3.1.240+4fa67d5](https://github.com/Hendrix-Shen/Tweak-My-Client/releases/tag/dev-240). Also fix #11.
