### ISSUE TITLE
[Bug] 自动重连 divide by zero 啦！

### ISSUE THREAD

**Issue by shenjackyuanjie** [Hendrix-Shen/Tweak-My-Client#15]
### Minecraft Version

1.18.2

### Tweak My Client Version

3.1.248+639bf15-beta

### Description

自动重连中，divide by zero啦！

### To Reproduce

java.lang.ArithmeticException: / by zero

### Expected behavior

别蹦（

### Log

![image](https://user-images.githubusercontent.com/54507071/177066004-afba7af0-fbfb-42b7-a507-78bd1fdeb0c3.png)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
尝试使用 [3.1.249+c546dd7](https://github.com/Hendrix-Shen/Tweak-My-Client/releases/tag/dev-249) 版本。
