### ISSUE TITLE
[Bug]  featureCustomWindowTitle not fully working at all 

### ISSUE THREAD

**Issue by MarkinhosMLP** [Hendrix-Shen/Tweak-My-Client#18]
### Minecraft Version

1.19.2

### Tweak My Client Version

the last one released

### Description

Custom Icons features does works but youre not able to change the image, as you were before. For some reason it stays the same gear icon no matter your resource pack

### To Reproduce

just try using a resource pack with an image named  "icon.png" 
>>>>> "assets/tweakmyclient/icon.png"

### Latest CI build tested

- [x] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
You are using the wrong path, the correct one should be in 
- `assets/tweakmyclient/texture/icon/icon_16x16.png`
- `assets/tweakmyclient/texture/icon/icon_32x32.png`

**Comment by MarkinhosMLP** [comment]
well... im using both of it... i said assets/tweakmyclient/icon.png" cause was the only one i found in the mod files... none of it works actually 
they always display that gear icon

![image](https://user-images.githubusercontent.com/47507632/195483500-bf513e3e-cc7a-46c0-b37d-9ffce1638a32.png)
![image](https://user-images.githubusercontent.com/47507632/195483517-2c24b29e-08b5-4230-b338-f508e6aee94a.png)

**Comment by Hendrix-Shen** [comment]
`assets/tweakmyclient/icon.png` is only for the display of icons in modmenu. If you wish to use it for `featureCustomWindowIcon` you must use the following path, I have tested it and it works.

> `assets/tweakmyclient/texture/icon/icon_16x16.png`
> `assets/tweakmyclient/texture/icon/icon_32x32.png`

**Comment by MarkinhosMLP** [comment]
> `assets/tweakmyclient/icon.png` is only for the display of icons in modmenu. If you wish to use it for `featureCustomWindowIcon` you must use the following path, I have tested it and it works.
> 
> > `assets/tweakmyclient/texture/icon/icon_16x16.png`
> > `assets/tweakmyclient/texture/icon/icon_32x32.png`

as i said, i was using both of it...

![image](https://user-images.githubusercontent.com/47507632/195505371-22b34ca8-ec89-4bd0-852e-63c1837a0e3b.png)

**Comment by Hendrix-Shen** [comment]
Don't you think there is something missing in your path?

It's `assets/tweakmyclient/texture/icon/icon_16x16.png` not `assets/tweakmyclient/icons/icon_16x16.png`.
