### ISSUE TITLE
Crash on 1.19

### ISSUE THREAD

**Issue by yt6983138** [Hendrix-Shen/Tweak-My-Client#19]
[latest.log](https://github.com/Hendrix-Shen/Tweak-My-Client/files/9843486/latest.log)

**Comment by Hendrix-Shen** [comment]
Sorry, this issue will not be fixed, because no updates will be made for non-latest release Minecraft.

**Comment by yt6983138** [comment]
ah ok

**Comment by yt6983138** [comment]
btw, does 1.19.2 version work on 1.19?

**Comment by Hendrix-Shen** [comment]
I don't think so.

**Comment by yt6983138** [comment]
ah ok
