### ISSUE TITLE
[Bug] 和玉 🔍Jade 🔍 不兼容

### ISSUE THREAD

**Issue by KiLiMe** [Hendrix-Shen/Tweak-My-Client#20]
### Minecraft Version

1.19.2

### Tweak My Client Version

3.2.268

### Description

Jade-1.19.1-fabric-8.6.0.jar 和 TweakMyClient-1.19.2-3.2.268+fc2ad10-stable.jar 启动游戏会崩溃

### To Reproduce

启动游戏稳定复现

### Log

[log.txt](https://github.com/Hendrix-Shen/Tweak-My-Client/files/10048401/log.txt)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
尝试这个版本 [3.4.291+5ae910f](https://github.com/Hendrix-Shen/Tweak-My-Client/releases/tag/dev-291)。

**Comment by KiLiMe** [comment]
> 尝试这个版本 [3.4.291+5ae910f](https://github.com/Hendrix-Shen/Tweak-My-Client/releases/tag/dev-291)。

现在工作正常,谢谢
