### ISSUE TITLE
[Feature Request] Disable delay after breaking block

### ISSUE THREAD

**Issue by ItzSkyReed** [Hendrix-Shen/Tweak-My-Client#25]
### What new features do you want?

Simple feature that will disable delay after breaking blocks

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
I recommend you to use [Nyan-Work/oh-my-minecraft-client](https://github.com/Nyan-Work/oh-my-minecraft-client).

**Comment by ItzSkyReed** [comment]
Thx
