### ISSUE TITLE
[Bug] 资源包加载问题

### ISSUE THREAD

**Issue by FlameFire26** [Hendrix-Shen/Tweak-My-Client#27]
### Minecraft Version

1.20.1

### Tweak My Client Version

3.6.398+b6a4f1b-stable

### Description

在 修补 中启用 禁用资源包兼容检查 后重启游戏会丢失所有原本不兼容资源包的选取（即移回左侧）

### To Reproduce

如上

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by shinyashen** [comment]
经过测试，https://github.com/Hendrix-Shen/Tweak-My-Client/commit/38c9a3426d4599f6877a0adb24a18c72636fcfa5 已经修复了此问题。
