### ISSUE TITLE
[Bug]造成xaero地图渲染错误

### ISSUE THREAD

**Issue by YehowahLiu** [Hendrix-Shen/Tweak-My-Client#3]
在加入这个模组后，xaero的小地图能够渲染实体/生物，但是地形全部变为黑色；同时打开大地图发现也全部为黑色，各种按钮能点击但点击后的相应gui无法渲染，退出大地图后不能正常显示游戏画面，要再次使用esc键才能到达退出世界的界面
版本:
minecraft 1.17.1
fabric loader 0.11.6
fabric api: 0.37.0
malilib: 0.10.0.dev23
tweak-my-client: 1.1.6+build.22
xaero's minimap 21.14.0
xaero's world map:1.15.0.1

**Comment by Hendrix-Shen** [comment]
Fix in 59b5d00
