### ISSUE TITLE
自定义方块轮廓无效

### ISSUE THREAD

**Issue by Maxhsly** [Hendrix-Shen/Tweak-My-Client#8]
您好，我目前所使用1.16.5及1.18.2客户端，均使用的2.0.201+de4112d-stable版tweak my client，而自定义方块轮廓这一功能无论在单机/服务器内均游戏中无效。

**Comment by Hendrix-Shen** [comment]
未能复现此问题

**Comment by Maxhsly** [comment]
可能为个人模组冲突所致，在更新至3.0.209已无此问题。
感谢您的回复。
