### ISSUE TITLE
自动丢弃这一功能的bug

### ISSUE THREAD

**Issue by Maxhsly** [Hendrix-Shen/Tweak-My-Client#9]
游戏版本1.16.5，模组版本2.0.201+de4112d-stable。
具体问题：选择黑名单无效，无视黑名单列表，包含默认列表内的物品同样会被丢出。
选择默认白名单有效，但修改新的白名单物品无效，即使添加新的白名单覆盖默认物品石头泥土等，仍丢出默认的泥土、石头。

**Comment by Hendrix-Shen** [comment]
尝试下3.0.209版本

**Comment by Maxhsly** [comment]
已解决，感谢您的回复。
